# SITE CONFIGURATION
title: Simon Phillips (spSlaine) # site's title
baseurl: ""
url: "https://splaine.github.io"
description: "A website with blog posts and pages" # used by search engines
name: Simon Phillips (spSlaine)

# Social Profiles
twitter_username:  sphillips
github_username:   spSlaine

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
